### ISSUE TITLE
Fix CSS gradient calculation

### ISSUE THREAD

**Issue by wolfbeast** [wolfbeast/Tycho#5]
FF38 uses pre-multiplied space by default. this needs to be reverted + my Goanna fixes re-implemented for transparent stops.

May also need reverting an "optimization" to prevent diagonal gradient issues re: https://bugzilla.mozilla.org/show_bug.cgi?id=895135

**Comment by wolfbeast** [comment]
Fixed by [808e10c] and [5580223] 

The root cause for the diagonal checkerboard issue on FF is premultiplication; with that reverted, the mentioned stop optimization doesn't cause any issues.

**Comment by mattatobin** [comment]
Blocks #33
